# Form implementation generated from reading ui file '../UI_files/inputPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import pyqtSignal
from torch.utils.data import DataLoader

from .Pages import Pages
from ..model.predict import run
from ..utils import DataFileLoad, DataLoad, VideoFrameDataset


class Ui_encoder(Pages):
    start_lr = 0
    end_lr = 0
    batch_size = 0
    window_size = 0
    input_url = []

    def __init__(self, encoPage):
        super().__init__()
        encoPage.setObjectName("Form")
        encoPage.resize(820, 531)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=encoPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 820, 520))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgWinLayout = QtWidgets.QHBoxLayout()
        self.imgWinLayout.setObjectName("horizontalLayout")

        self.orgImgWin = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.orgImgWin.setMinimumSize(QtCore.QSize(300, 300))
        self.orgImgWin.setObjectName("widget")
        self.imgWinLayout.addWidget(self.orgImgWin)

        self.recImgWin = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.recImgWin.setMinimumSize(QtCore.QSize(300, 300))
        self.recImgWin.setObjectName("widget_2")
        self.imgWinLayout.addWidget(self.recImgWin)
        self.verticalLayout.addLayout(self.imgWinLayout)

        self.terminalLayout = QtWidgets.QHBoxLayout()
        self.terminalLayout.setSpacing(10)
        self.terminalLayout.setObjectName("horizontalLayout_2")

        self.operatorLayout = QtWidgets.QVBoxLayout()
        self.operatorLayout.setObjectName("verticalLayout_2")

        self.parameterLayout = QtWidgets.QVBoxLayout()
        self.parameterLayout.setSpacing(10)
        self.parameterLayout.setObjectName("verticalLayout_3")

        self.startLrLayout = QtWidgets.QHBoxLayout()
        self.startLrLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.startLrLayout.setSpacing(0)
        self.startLrLayout.setObjectName("horizontalLayout_4")
        self.text_startLr = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_startLr.sizePolicy().hasHeightForWidth())
        self.text_startLr.setSizePolicy(sizePolicy)
        self.text_startLr.setMaximumSize(QtCore.QSize(200, 30))
        self.text_startLr.setObjectName("textBrowser_2")
        self.startLrLayout.addWidget(self.text_startLr)

        self.startLrSpin = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.startLrSpin.setMinimumSize(QtCore.QSize(200, 30))
        self.startLrSpin.setObjectName("doubleSpinBox")
        self.startLrSpin.setDecimals(8)
        self.startLrSpin.setValue(0.0001)
        self.startLrSpin.setSingleStep(0.00001)
        self.startLrLayout.addWidget(self.startLrSpin)
        self.parameterLayout.addLayout(self.startLrLayout)

        self.endLrLayout = QtWidgets.QHBoxLayout()
        self.endLrLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.endLrLayout.setSpacing(0)
        self.endLrLayout.setObjectName("horizontalLayout_8")
        self.text_endLr = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHeightForWidth(self.text_endLr.sizePolicy().hasHeightForWidth())
        self.text_endLr.setSizePolicy(sizePolicy)
        self.text_endLr.setMaximumSize(QtCore.QSize(200, 30))
        self.text_endLr.setObjectName("textBrowser_3")

        self.endLrLayout.addWidget(self.text_endLr)
        self.endLrSpin = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.endLrSpin.setMinimumSize(QtCore.QSize(200, 30))
        self.endLrSpin.setObjectName("doubleSpinBox_2")
        self.endLrSpin.setDecimals(8)
        self.endLrSpin.setValue(0.0001)
        self.endLrSpin.setSingleStep(0.00001)
        self.endLrLayout.addWidget(self.endLrSpin)
        self.parameterLayout.addLayout(self.endLrLayout)

        self.wsLayout = QtWidgets.QHBoxLayout()
        self.wsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.wsLayout.setSpacing(0)
        self.wsLayout.setObjectName("horizontalLayout_9")
        self.text_ws = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHeightForWidth(self.text_ws.sizePolicy().hasHeightForWidth())
        self.text_ws.setSizePolicy(sizePolicy)
        self.text_ws.setMaximumSize(QtCore.QSize(200, 30))
        self.text_ws.setObjectName("textBrowser_6")

        self.wsLayout.addWidget(self.text_ws)
        self.wsSpin = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.wsSpin.setMinimumSize(QtCore.QSize(200, 30))
        self.wsSpin.setObjectName("doubleSpinBox_4")
        self.wsSpin.setMaximum(1000)
        self.wsSpin.setMinimum(1)
        self.wsSpin.setSingleStep(1)
        self.wsSpin.setValue(100)
        self.wsLayout.addWidget(self.wsSpin)
        self.parameterLayout.addLayout(self.wsLayout)

        self.bsLayout = QtWidgets.QHBoxLayout()
        self.bsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.bsLayout.setSpacing(0)
        self.bsLayout.setObjectName("horizontalLayout_5")
        self.text_bs = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHeightForWidth(self.text_bs.sizePolicy().hasHeightForWidth())
        self.text_bs.setSizePolicy(sizePolicy)
        self.text_bs.setMaximumSize(QtCore.QSize(200, 30))
        self.text_bs.setObjectName("textBrowser_4")
        self.bsLayout.addWidget(self.text_bs)
        self.bsSpin = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.bsSpin.setMinimumSize(QtCore.QSize(150, 30))
        self.bsSpin.setObjectName("doubleSpinBox_3")
        self.bsSpin.setMaximum(100)
        self.bsSpin.setMinimum(1)
        self.bsSpin.setSingleStep(1)
        self.bsSpin.setValue(10)
        self.bsLayout.addWidget(self.bsSpin)
        self.parameterLayout.addLayout(self.bsLayout)

        self.operatorLayout.addLayout(self.parameterLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.buttonLayout.setContentsMargins(0, 5, 0, 5)
        self.buttonLayout.setSpacing(5)
        self.buttonLayout.setObjectName("horizontalLayout_3")

        buttonSizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                                 QtWidgets.QSizePolicy.Policy.Minimum)
        self.confirmButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.confirmButton.setObjectName("pushButton")
        self.confirmButton.setSizePolicy(buttonSizePolicy)
        self.buttonLayout.addWidget(self.confirmButton)
        self.trainButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.trainButton.setObjectName("pushButton_2")
        self.trainButton.setSizePolicy(buttonSizePolicy)
        self.buttonLayout.addWidget(self.trainButton)
        self.testButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.testButton.setObjectName("pushButton")
        self.testButton.setSizePolicy(buttonSizePolicy)
        self.buttonLayout.addWidget(self.testButton)

        self.clearButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.clearButton.setObjectName("pushButton")
        self.clearButton.setSizePolicy(buttonSizePolicy)
        self.buttonLayout.addWidget(self.clearButton)
        self.operatorLayout.addLayout(self.buttonLayout)

        self.terminalLayout.addLayout(self.operatorLayout)

        self.textBrowser = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(400, 16777215))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.terminalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.terminalLayout)

        self.retranslateUi(encoPage)
        QtCore.QMetaObject.connectSlotsByName(encoPage)

    def receive_url(self, input_url):
        self.input_url = input_url

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text_startLr.setText("Start Learning Rate")
        self.text_endLr.setText("End Learning Rate")
        self.text_bs.setText("Batch Size")
        self.text_ws.setText("Slide Window Size")

        self.clearButton.setText(_translate("Form", "Clear"))
        self.trainButton.setText(_translate("Form", "Train"))
        self.testButton.setText(_translate("Form", "Test"))
        self.confirmButton.setText(_translate("Form", "Confirm Parameters"))

        self.trainButton.setEnabled(False)
        self.testButton.setEnabled(False)
        self.clearButton.setEnabled(True)

        self.confirmButton.clicked.connect(lambda: self.confirm_parameter())
        self.clearButton.clicked.connect(lambda: self.clear_parameter())

    def confirm_parameter(self):
        self.trainButton.setEnabled(True)
        self.testButton.setEnabled(True)
        self.clearButton.setEnabled(True)
        self.confirmButton.setEnabled(False)

        self.trainButton.clicked.connect(lambda: self.autoencoder_train_pipeline())

        self.bsSpin.setEnabled(False)
        self.wsSpin.setEnabled(False)
        self.startLrSpin.setEnabled(False)
        self.endLrSpin.setEnabled(False)

        self.window_size = self.wsSpin.value()
        self.batch_size = self.bsSpin.value()
        self.start_lr = self.startLrSpin.value()
        self.end_lr = self.endLrSpin.value()

    def clear_parameter(self):
        self.trainButton.setEnabled(False)
        self.testButton.setEnabled(False)
        self.confirmButton.setEnabled(True)
        self.clearButton.setEnabled(True)

        self.bsSpin.setEnabled(True)
        self.wsSpin.setEnabled(True)
        self.startLrSpin.setEnabled(True)
        self.endLrSpin.setEnabled(True)

        self.startLrSpin.setValue(0.0001)
        self.endLrSpin.setValue(0.0001)
        self.wsSpin.setValue(100)
        self.bsSpin.setValue(10)

    def send_data(self, str_data):
        self._signal.emit(str_data)

    def autoencoder_train_pipeline(self):
        if len(self.input_url) == 0 or (len(self.input_url) != 0 and len(self.input_url[0]) != len(self.input_url[1])):
            self.send_data("Invalid Input! Please Input Again")
        else:
            kargs = {"train_video_path": self.input_url[0], "train_label_path": self.input_url[1],
                    "test_video_path": "", "test_label_path": "", "weight": None, "window_size": self.window_size,
                    "batch_size": self.batch_size, "win_stride": 2, "imgz": (25, 25), "device": " mps", "name": 'exp',
                    "autoencode": True, "predict": False, "train": True, "test": False, "save": False}
            run(**kargs)


