# Form implementation generated from reading ui file '../UI_files/inputPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from .Pages import Pages

'''
Description: Model Page provides main entrance to construct the neuron network architecture for model training
The default architecture provides the default nn architecture for user to train with their own train set

The load architecture requires user to select a cfg file including their own architecture, but also provide a graphical
approach to built a cfg architecture file

The load Model allows user to directly load a pytorch model for further training and directly testing
'''


class Ui_model(Pages):
    encoderLayers = []
    predictorLayers = []
    def __init__(self, modelPage):
        super().__init__()
        modelPage.setObjectName("Form")
        self.tabWidget = QtWidgets.QTabWidget(parent=modelPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 820, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.DefaultTab = QtWidgets.QWidget()
        self.DefaultTab.setObjectName("tab")

        ## Content In Tab 1
        self.DefaultWidget = QtWidgets.QWidget(parent=self.DefaultTab)
        self.DefaultWidget.setGeometry(QtCore.QRect(0, 0, 811, 501))
        self.DefaultWidget.setObjectName("horizontalLayoutWidget")

        self.OverallLayout = QtWidgets.QHBoxLayout(self.DefaultWidget)
        self.OverallLayout.setContentsMargins(5, 5, 5, 5)
        self.OverallLayout.setObjectName("horizontalLayout")

        self.EncoderLayout = QtWidgets.QVBoxLayout()
        self.EncoderLayout.setObjectName("EncoderLayout")
        self.EncoderLabel = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.EncoderLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.EncoderLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.EncoderLabel.setMidLineWidth(0)
        self.EncoderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.EncoderLabel.setObjectName("EncoderLabel")
        self.EncoderLayout.addWidget(self.EncoderLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.EncoderLabelTxt = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.EncoderLabelTxt.setMaximumSize(QtCore.QSize(110, 15))
        self.EncoderLabelTxt.setObjectName("EncoderLabelTxt")
        self.EncoderLabelTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)

        self.horizontalLayout_6.addWidget(self.EncoderLabelTxt)
        self.EncoderLabelIn = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.EncoderLabelIn.setMaximumSize(QtCore.QSize(16777215, 15))
        self.EncoderLabelIn.setObjectName("EncoderLabelIn")
        self.EncoderLabelIn.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_6.addWidget(self.EncoderLabelIn)

        self.EncoderLabelOut = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.EncoderLabelOut.setMaximumSize(QtCore.QSize(16777215, 15))
        self.EncoderLabelOut.setObjectName("EncoderLabelOut")
        self.EncoderLabelOut.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_6.addWidget(self.EncoderLabelOut)
        self.EncoderLayout.addLayout(self.horizontalLayout_6)

        self.enLayerLayout = QtWidgets.QVBoxLayout()
        self.enLayerLayout.setObjectName("LayerLayout")
        self.EncoderLayout.addLayout(self.enLayerLayout)

        self.encodeButtonLayout = QtWidgets.QHBoxLayout()
        self.encodeButtonLayout.setObjectName("EncoderButtonLayout")
        self.encoderAdd = QtWidgets.QPushButton(parent=self.DefaultWidget)
        self.encoderAdd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.encoderAdd.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.encoderAdd.setObjectName("encoderAdd")
        self.encodeButtonLayout.addWidget(self.encoderAdd)

        self.encoderClear = QtWidgets.QPushButton(parent=self.DefaultWidget)
        self.encoderClear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.encoderClear.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.encoderClear.setObjectName("encoderClear")
        self.encodeButtonLayout.addWidget(self.encoderClear)
        self.EncoderLayout.addLayout(self.encodeButtonLayout)
        self.addOneLayer(self.enLayerLayout, self.encoderAdd)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.EncoderLayout.addLayout(self.horizontalLayout_4)
        self.EncoderLayout.addStretch()
        self.OverallLayout.addLayout(self.EncoderLayout)

        self.PredictorLayout = QtWidgets.QVBoxLayout()
        self.PredictorLayout.setObjectName("PredictorLayout")
        self.PredictorLabel = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.PredictorLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.PredictorLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.PredictorLabel.setMidLineWidth(0)
        self.PredictorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.PredictorLabel.setObjectName("PredictorLabel")
        self.PredictorLayout.addWidget(self.PredictorLabel)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PredictorTxt = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.PredictorTxt.setMaximumSize(QtCore.QSize(110, 15))
        self.PredictorTxt.setObjectName("PredictorTxt")
        self.PredictorTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_7.addWidget(self.PredictorTxt)

        self.PredictorLabelIn = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.PredictorLabelIn.setMaximumSize(QtCore.QSize(16777215, 15))
        self.PredictorLabelIn.setObjectName("PredictorLabelIn")
        self.PredictorLabelIn.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_7.addWidget(self.PredictorLabelIn)

        self.PredictorLabelOut = QtWidgets.QLabel(parent=self.DefaultWidget)
        self.PredictorLabelOut.setMaximumSize(QtCore.QSize(16777215, 15))
        self.PredictorLabelOut.setObjectName("PredictorLabelOut")
        self.PredictorLabelOut.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_7.addWidget(self.PredictorLabelOut)
        self.PredictorLayout.addLayout(self.horizontalLayout_7)

        self.preLayerLayout = QtWidgets.QVBoxLayout()
        self.preLayerLayout.setObjectName("LayerLayout")
        self.PredictorLayout.addLayout(self.preLayerLayout)

        self.preButtonLayout = QtWidgets.QHBoxLayout()
        self.preButtonLayout.setObjectName("preButtonLayout")
        self.predictorAdd = QtWidgets.QPushButton(parent=self.DefaultWidget)
        self.predictorAdd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.predictorAdd.setObjectName("predictorAdd")
        self.preButtonLayout.addWidget(self.predictorAdd)

        self.predictorClear = QtWidgets.QPushButton(parent=self.DefaultWidget)
        self.predictorClear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.predictorClear.setObjectName("predictorClear")
        self.preButtonLayout.addWidget(self.predictorClear)
        self.PredictorLayout.addLayout(self.preButtonLayout)
        self.addOneLayer(self.preLayerLayout, self.predictorAdd)


        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PredictorLayout.addLayout(self.horizontalLayout_8)
        self.PredictorLayout.addStretch()
        self.OverallLayout.addLayout(self.PredictorLayout)
        self.tabWidget.addTab(self.DefaultTab, "")


        # Tab 2
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(modelPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(modelPage)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.EncoderLabel.setText(_translate("Form", "Encoder and Decoder Architecture"))
        self.EncoderLabelTxt.setText(_translate("Form", "Linear Layers"))
        self.EncoderLabelIn.setText(_translate("Form", "Input Nodes"))
        self.EncoderLabelOut.setText(_translate("Form", "Output Nodes"))
        self.encoderAdd.setText("Add One Layer")
        self.encoderClear.setText("Clear Layers")
        self.PredictorLabel.setText("Predictor Architecture")
        self.PredictorTxt.setText("Linear Layers")
        self.PredictorLabelIn.setText("Input Nodes")
        self.PredictorLabelOut.setText("Output Nodes")
        self.predictorAdd.setText("Add One Layer")
        self.predictorClear.setText("Clear Layers")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DefaultTab), "Default Architecture")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), "Load Architecture")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), "Load Model")

        self.encoderAdd.clicked.connect(lambda: self.addOneLayer(self.enLayerLayout, self.encoderAdd))
        self.encoderClear.clicked.connect(lambda: self.clear_Layers(self.enLayerLayout, self.encoderAdd))
        self.predictorAdd.clicked.connect(lambda: self.addOneLayer(self.preLayerLayout, self.predictorAdd))
        self.predictorClear.clicked.connect(lambda: self.clear_Layers(self.preLayerLayout, self.predictorAdd))

    def addOneLayer(self, targetLayout, targetButton: QtWidgets.QPushButton):
        count = targetLayout.count()
        if count == 0:
            text = "Input Layer"
        else:
            text = "Hidden Layer " + str(count)
        layerLayout = QtWidgets.QHBoxLayout()
        layerLayout.setObjectName("horizontalLayout_2")
        EncoderTxt = QtWidgets.QTextBrowser(parent=self.DefaultWidget)
        EncoderTxt.setMaximumSize(QtCore.QSize(110, 30))
        EncoderTxt.setObjectName("EncoderTxt")
        EncoderTxt.setText(text)
        layerLayout.addWidget(EncoderTxt)

        encoderSpinIn = QtWidgets.QSpinBox(parent=self.DefaultWidget)
        encoderSpinIn.setMinimumSize(QtCore.QSize(0, 30))
        encoderSpinIn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        encoderSpinIn.setObjectName("encoderSpinIn")
        encoderSpinIn.setMaximum(10000)
        encoderSpinIn.setMinimum(1)
        encoderSpinIn.setSingleStep(1)
        layerLayout.addWidget(encoderSpinIn)

        encoderSpinOut = QtWidgets.QSpinBox(parent=self.DefaultWidget)
        encoderSpinOut.setMinimumSize(QtCore.QSize(0, 30))
        encoderSpinOut.setMaximumSize(QtCore.QSize(16777215, 16777215))
        encoderSpinOut.setObjectName("encoderSpinOut")
        encoderSpinOut.setMaximum(10000)
        encoderSpinOut.setMinimum(1)
        encoderSpinOut.setSingleStep(1)
        layerLayout.addWidget(encoderSpinOut)
        targetLayout.addLayout(layerLayout)
        if targetLayout.count() == 10:
            targetButton.setEnabled(False)

    def clear_Layers(self, parent_layout: QtWidgets, targetButton: QtWidgets.QPushButton):
        # 保留第一个布局，从第二个开始移除
        while parent_layout.count() > 1:
            # 获取第二个布局项（索引为1）
            layout_item = parent_layout.itemAt(1)
            # 移除并删除这个布局项
            if layout_item.layout() is not None:
                # 移除布局中的所有小部件
                self.clear_layout(layout_item.layout())
                # 移除布局本身
                layout_item.layout().deleteLater()
            parent_layout.removeItem(layout_item)
        targetButton.setEnabled(True)

    def clear_layout(self, layout):
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
            elif item.layout() is not None:
                self.clear_layout(item.layout())