# Form implementation generated from reading ui file '../UI_files/inputPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from .Pages import Pages

'''
Description: Model Page provides main entrance to construct the neuron network architecture for model training
The default architecture provides the default nn architecture for user to train with their own train set

The load architecture requires user to select a cfg file including their own architecture, but also provide a graphical
approach to built a cfg architecture file

The load Model allows user to directly load a pytorch model for further training and directly testing
'''
class Ui_model(Pages):
    def __init__(self, Form):
        super().__init__()
        Form.setObjectName("Form")
        Form.resize(800, 528)
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(5, 5, 790, 508))
        self.tabWidget.setObjectName("tabWidget")
        self.default = QtWidgets.QWidget()
        self.default.setObjectName("tab")
        self.tabWidget.addTab(self.default, "")
        self.custom = QtWidgets.QWidget()
        self.custom.setObjectName("tab_3")
        self.tabWidget.addTab(self.custom, "")
        self.loadModel = QtWidgets.QWidget()
        self.loadModel.setObjectName("tab_3")
        self.tabWidget.addTab(self.loadModel, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.default), _translate("Form", "Default Architecture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.custom), _translate("Form", "Load Architecture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loadModel), _translate("Form", "Load Model"))



