# Form implementation generated from reading ui file '../UI_files/inputPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from .Pages import Pages

class Ui_pred(Pages):
    def __init__(self, inpPage):
        super().__init__()
        inpPage.setObjectName("Form")
        inpPage.resize(820, 531)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=inpPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 820, 520))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.overallLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.overallLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.overallLayout.setContentsMargins(5, 5, 5, 5)
        self.overallLayout.setObjectName("overallLayout")
        self.infoLayout = QtWidgets.QHBoxLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.processLayout = QtWidgets.QVBoxLayout()
        self.processLayout.setSpacing(5)
        self.processLayout.setObjectName("processLayout")
        self.progressBar = QtWidgets.QProgressBar(parent=self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setStyleSheet(
            "QProgressBar { border: 2px solid grey; border-radius: 5px; color: rgb(20,20,20);  background-color: "
            "#FFFFFF; text-align: center;}QProgressBar::chunk {background-color: rgb(100,200,200); border-radius: "
            "10px; margin: 0.1px;  width: 1px;}")
        self.processLayout.addWidget(self.progressBar)
        self.trainProcessTxt = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        self.trainProcessTxt.setMinimumSize(QtCore.QSize(400, 0))
        self.trainProcessTxt.setMaximumSize(QtCore.QSize(400, 275))
        self.trainProcessTxt.setObjectName("trainProcessTxt")
        self.processLayout.addWidget(self.trainProcessTxt)
        self.infoLayout.addLayout(self.processLayout)
        self.graphicShow = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.graphicShow.setMinimumSize(QtCore.QSize(400, 0))
        self.graphicShow.setMaximumSize(QtCore.QSize(400, 16777215))
        self.graphicShow.setObjectName("graphicShow")
        self.infoLayout.addWidget(self.graphicShow)
        self.overallLayout.addLayout(self.infoLayout)
        self.terminalLayout = QtWidgets.QHBoxLayout()
        self.terminalLayout.setSpacing(0)
        self.terminalLayout.setObjectName("terminalLayout")
        self.parameterLayout = QtWidgets.QVBoxLayout()
        self.parameterLayout.setObjectName("parameterLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startLrLayout = QtWidgets.QHBoxLayout()
        self.startLrLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.startLrLayout.setSpacing(0)
        self.startLrLayout.setObjectName("startLrLayout")
        self.startLrTxt = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startLrTxt.sizePolicy().hasHeightForWidth())
        self.startLrTxt.setSizePolicy(sizePolicy)
        self.startLrTxt.setMaximumSize(QtCore.QSize(200, 30))
        self.startLrTxt.setObjectName("startLrTxt")
        self.startLrLayout.addWidget(self.startLrTxt)
        self.startLrSpinBox = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.startLrSpinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.startLrSpinBox.setDecimals(10)
        self.startLrSpinBox.setMaximum(1.0)
        self.startLrSpinBox.setSingleStep(1e-05)
        self.startLrSpinBox.setStepType(QtWidgets.QAbstractSpinBox.StepType.DefaultStepType)
        self.startLrSpinBox.setProperty("value", 0.0001)
        self.startLrSpinBox.setObjectName("startLrSpinBox")
        self.startLrLayout.addWidget(self.startLrSpinBox)
        self.verticalLayout_3.addLayout(self.startLrLayout)
        self.endLrLayout = QtWidgets.QHBoxLayout()
        self.endLrLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.endLrLayout.setSpacing(0)
        self.endLrLayout.setObjectName("endLrLayout")
        self.endLrTxt = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endLrTxt.sizePolicy().hasHeightForWidth())
        self.endLrTxt.setSizePolicy(sizePolicy)
        self.endLrTxt.setMaximumSize(QtCore.QSize(200, 30))
        self.endLrTxt.setObjectName("endLrTxt")
        self.endLrLayout.addWidget(self.endLrTxt)
        self.endLrSpinBox = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.endLrSpinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.endLrSpinBox.setDecimals(10)
        self.endLrSpinBox.setMaximum(1.0)
        self.endLrSpinBox.setSingleStep(1e-05)
        self.endLrSpinBox.setProperty("value", 1e-05)
        self.endLrSpinBox.setObjectName("endLrSpinBox")
        self.endLrLayout.addWidget(self.endLrSpinBox)
        self.verticalLayout_3.addLayout(self.endLrLayout)
        self.wsLayout = QtWidgets.QHBoxLayout()
        self.wsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.wsLayout.setSpacing(0)
        self.wsLayout.setObjectName("wsLayout")
        self.wsTxt = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wsTxt.sizePolicy().hasHeightForWidth())
        self.wsTxt.setSizePolicy(sizePolicy)
        self.wsTxt.setMaximumSize(QtCore.QSize(200, 30))
        self.wsTxt.setObjectName("wsTxt")
        self.wsLayout.addWidget(self.wsTxt)

        self.wsSpinBox = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.wsSpinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.wsSpinBox.setObjectName("wsSpinBox")
        self.wsSpinBox.setMaximum(9000)
        self.wsSpinBox.setMinimum(0)
        self.wsSpinBox.setSingleStep(1)
        self.wsSpinBox.setValue(100)
        self.wsLayout.addWidget(self.wsSpinBox)

        self.verticalLayout_3.addLayout(self.wsLayout)
        self.bsLayout = QtWidgets.QHBoxLayout()
        self.bsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.bsLayout.setSpacing(0)
        self.bsLayout.setObjectName("bsLayout")
        self.bsTxt = QtWidgets.QTextBrowser(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsTxt.sizePolicy().hasHeightForWidth())
        self.bsTxt.setSizePolicy(sizePolicy)
        self.bsTxt.setMaximumSize(QtCore.QSize(200, 30))
        self.bsTxt.setObjectName("bsTxt")
        self.bsLayout.addWidget(self.bsTxt)
        self.bsSpinBox = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.bsSpinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.bsSpinBox.setMaximum(1000)
        self.bsSpinBox.setProperty("value", 10)
        self.bsSpinBox.setObjectName("bsSpinBox")
        self.bsLayout.addWidget(self.bsSpinBox)
        self.verticalLayout_3.addLayout(self.bsLayout)
        self.parameterLayout.addLayout(self.verticalLayout_3)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.buttonLayout.setContentsMargins(0, 5, 0, 5)
        self.buttonLayout.setSpacing(5)
        self.buttonLayout.setObjectName("buttonLayout")
        SizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                                 QtWidgets.QSizePolicy.Policy.Minimum)
        self.confirmButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.confirmButton.setSizePolicy(SizePolicy)
        self.confirmButton.setObjectName("confirmButton")
        self.buttonLayout.addWidget(self.confirmButton)

        self.pauseTrainButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pauseTrainButton.setSizePolicy(SizePolicy)
        self.pauseTrainButton.setObjectName("pauseTrainButton")
        self.pauseTrainButton.setVisible(False)
        self.buttonLayout.addWidget(self.pauseTrainButton)

        self.startTrainButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.startTrainButton.setSizePolicy(SizePolicy)
        self.startTrainButton.setObjectName("startTrainButton")
        self.startTrainButton.setEnabled(False)
        self.buttonLayout.addWidget(self.startTrainButton)

        self.startTestButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.startTestButton.setSizePolicy(SizePolicy)
        self.startTestButton.setObjectName("startTestButton")
        self.startTestButton.setEnabled(False)
        self.buttonLayout.addWidget(self.startTestButton)

        self.pauseTestButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pauseTestButton.setSizePolicy(SizePolicy)
        self.pauseTestButton.setObjectName("pauseTestButton")
        self.pauseTestButton.setVisible(False)
        self.buttonLayout.addWidget(self.pauseTestButton)

        self.clearButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.clearButton.setSizePolicy(SizePolicy)
        self.clearButton.setObjectName("clearButton")
        self.buttonLayout.addWidget(self.clearButton)
        self.parameterLayout.addLayout(self.buttonLayout)

        self.terminalLayout.addLayout(self.parameterLayout)
        self.spikeTimeShow = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.spikeTimeShow.setMinimumSize(QtCore.QSize(400, 0))
        self.spikeTimeShow.setObjectName("spikeTimeShow")
        self.terminalLayout.addWidget(self.spikeTimeShow)
        self.overallLayout.addLayout(self.terminalLayout)

        self.retranslateUi(inpPage)
        self.connection()
        QtCore.QMetaObject.connectSlotsByName(inpPage)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startLrTxt.setHtml(_translate("Form", "Start Learning Rate"))
        self.endLrTxt.setHtml(_translate("Form", "Final Learning Rate"))
        self.wsTxt.setText(_translate("Form", "Window Size"))
        self.bsTxt.setText(_translate("Form", "Batch Size"))
        self.confirmButton.setText(_translate("Form", "Confirm Parameter"))
        self.pauseTrainButton.setText(_translate("Form", "Pause"))
        self.startTrainButton.setText(_translate("Form", "Train"))
        self.startTestButton.setText(_translate("Form", "Test"))
        self.pauseTestButton.setText(_translate("Form", "Pause"))
        self.clearButton.setText(_translate("Form", "Clear"))

    def connection(self):
        self.confirmButton.clicked.connect(self.confirm_parameter)
        self.startTrainButton.clicked.connect(self.start_train)
        self.pauseTrainButton.clicked.connect(self.pause_train)
        self.startTestButton.clicked.connect(self.start_test)
        self.pauseTestButton.clicked.connect(self.pause_test)
        self.clearButton.clicked.connect(self.clear_all)

    def confirm_parameter(self):
        ##
        self.confirmButton.setEnabled(False)
        self.startTrainButton.setEnabled(True)
        self.startTestButton.setEnabled(True)

    def start_train(self):
        ##
        self.startTrainButton.setVisible(False)
        self.pauseTrainButton.setVisible(True)

    def pause_train(self):
        ##
        self.startTrainButton.setVisible(True)
        self.pauseTrainButton.setVisible(False)

    def start_test(self):
        ##
        self.startTestButton.setVisible(False)
        self.pauseTestButton.setVisible(True)

    def pause_test(self):
        ##
        self.startTestButton.setVisible(True)
        self.pauseTestButton.setVisible(False)

    def clear_all(self):
        self.confirmButton.setEnabled(True)
        self.startTestButton.setVisible(True)
        self.startTestButton.setEnabled(False)
        self.pauseTestButton.setVisible(False)

        self.startTrainButton.setVisible(True)
        self.startTrainButton.setEnabled(False)
        self.pauseTrainButton.setVisible(False)
        
    def closeEvent(self, event):
        super().closeEvent(event)

